import Card, { CardContent } from '@/components/ui/Card';
import ScrollReveal from '@/components/common/ScrollReveal';
import { fallbackClubSettings } from '@/lib/club-settings-types';
import { getClubSettings } from '@/lib/club-settings';
import { getContentBlocks } from '@/lib/content-blocks';
import { getCommitteeMembers, type CommitteeMemberContent } from '@/lib/structured-content';
import ContactUpcomingEvents from '@/components/calendar/ContactUpcomingEvents';
import ContactForm from './ContactForm';

// Server component: CMS copy, club settings and the committee list are read
// server-side (same sources as /api/content-blocks, /api/club-settings and
// /api/public/committee) and regenerated by the segment's ISR config in
// ./layout.tsx. Only the enquiry form is a client island.

// Used in the "email notification failed" notice when club settings carry no
// email address.
// Urgent follow-up goes to the secretary inbox, as before the page moved to
// server rendering (the club settings address is shown separately below).
const URGENT_EMAIL = 'ndcc.secretary1@gmail.com';

async function loadCommittee(): Promise<CommitteeMemberContent[]> {
  try {
    const members = await getCommitteeMembers();
    return Array.isArray(members) ? members : [];
  } catch {
    return [];
  }
}

export default async function ContactPage() {
  const [blocks, settings, committee] = await Promise.all([
    getContentBlocks(['contact.hero', 'contact.form_intro', 'contact.details']),
    getClubSettings(),
    loadCommittee(),
  ]);
  const heroTitle = blocks['contact.hero']?.title || 'Contact Us';
  const heroBody = blocks['contact.hero']?.body || 'Have a question, want to join, or looking to get involved? We’d love to hear from you.';
  const formIntro = blocks['contact.form_intro']?.body || 'Fill out the form below and we’ll get back to you as soon as possible.';
  const detailsTitle = blocks['contact.details']?.title || 'Club Details';

  const clubPhoneHref = settings.phone ? `tel:${settings.phone.replace(/\s+/g, '')}` : undefined;

  return (
    <>
      {/* Hero */}
      <section className="page-hero">
        <div className="container-width">
          <ScrollReveal onMount delay={0}><h1 className="page-hero-title">{heroTitle}</h1></ScrollReveal>
          <ScrollReveal onMount delay={0.15}><p className="page-hero-subtitle">{heroBody}</p></ScrollReveal>
        </div>
      </section>

      {/* Contact Form + Details */}
      <section className="section-padding">
        <div className="container-width">
          <ScrollReveal>
          <div className="grid grid-cols-1 lg:grid-cols-2 gap-12">
            {/* Form Column */}
            <div>
              <h2 className="section-title">Send Us a Message</h2>
              <p className="text-content-muted font-body mb-8">{formIntro}</p>
              <ContactForm urgentEmail={URGENT_EMAIL} />
            </div>

            {/* Details Column */}
            <div className="space-y-8">
              {/* Address */}
              <Card>
                <CardContent className="p-6">
                  <h3 className="text-xl font-display font-bold text-content-primary mb-4">{detailsTitle}</h3>
                  <div className="space-y-4">
                    <div className="flex items-start gap-3">
                      <svg className="w-5 h-5 text-maroon-600 dark:text-maroon-300 mt-0.5 flex-shrink-0" fill="none" viewBox="0 0 24 24" strokeWidth={1.5} stroke="currentColor" aria-hidden="true">
                        <path strokeLinecap="round" strokeLinejoin="round" d="M15 10.5a3 3 0 1 1-6 0 3 3 0 0 1 6 0Z" />
                        <path strokeLinecap="round" strokeLinejoin="round" d="M19.5 10.5c0 7.142-7.5 11.25-7.5 11.25S4.5 17.642 4.5 10.5a7.5 7.5 0 1 1 15 0Z" />
                      </svg>
                      <div>
                        <p className="font-body font-semibold text-content-primary">{settings.ground_name}</p>
                        <p className="font-body text-content-muted text-sm">{settings.address}</p>
                      </div>
                    </div>
                    <div className="flex items-start gap-3">
                      <svg className="w-5 h-5 text-maroon-600 dark:text-maroon-300 mt-0.5 flex-shrink-0" fill="none" viewBox="0 0 24 24" strokeWidth={1.5} stroke="currentColor" aria-hidden="true">
                        <path strokeLinecap="round" strokeLinejoin="round" d="M2.25 6.75c0-1.243 1.007-2.25 2.25-2.25h2.268c1.141 0 2.116.816 2.317 1.939l.734 4.117a2.25 2.25 0 0 1-.96 2.281l-1.53 1.02a11.042 11.042 0 0 0 5.523 5.523l1.02-1.53a2.25 2.25 0 0 1 2.281-.96l4.117.734a2.25 2.25 0 0 1 1.939 2.317V19.5a2.25 2.25 0 0 1-2.25 2.25h-.75C10.3 21.75 2.25 13.7 2.25 3.75v3Z" />
                      </svg>
                      <div>
                        <p className="font-body font-semibold text-content-primary">Contact</p>
                        <a
                          href={clubPhoneHref}
                          className="font-body text-maroon-700 dark:text-maroon-200 hover:text-maroon-500 text-sm transition-colors"
                        >
                          {settings.phone}
                        </a>
                      </div>
                    </div>
                    <div className="flex items-start gap-3">
                      <svg className="w-5 h-5 text-maroon-600 dark:text-maroon-300 mt-0.5 flex-shrink-0" fill="none" viewBox="0 0 24 24" strokeWidth={1.5} stroke="currentColor" aria-hidden="true">
                        <path strokeLinecap="round" strokeLinejoin="round" d="M21.75 6.75v10.5a2.25 2.25 0 0 1-2.25 2.25h-15a2.25 2.25 0 0 1-2.25-2.25V6.75m19.5 0A2.25 2.25 0 0 0 19.5 4.5h-15a2.25 2.25 0 0 0-2.25 2.25m19.5 0v.243a2.25 2.25 0 0 1-1.07 1.916l-7.5 4.615a2.25 2.25 0 0 1-2.36 0L3.32 8.91a2.25 2.25 0 0 1-1.07-1.916V6.75" />
                      </svg>
                      <div>
                        <p className="font-body font-semibold text-content-primary">Email</p>
                        <a
                          href={settings.email ? `mailto:${settings.email}` : undefined}
                          className="font-body text-maroon-700 dark:text-maroon-200 hover:text-maroon-500 text-sm transition-colors"
                        >
                          {settings.email}
                        </a>
                      </div>
                    </div>
                  </div>
                </CardContent>
              </Card>


              {/* Social Links */}
              <Card>
                <CardContent className="p-6">
                  <h3 className="text-xl font-display font-bold text-content-primary mb-4">Social Links</h3>
                  <div className="space-y-2">
                    {settings.facebook_url && (
                      <a
                        href={settings.facebook_url}
                        target="_blank"
                        rel="noopener noreferrer"
                        className="block font-body text-maroon-700 dark:text-maroon-200 hover:text-maroon-500 text-sm transition-colors"
                      >
                        Facebook
                      </a>
                    )}
                    {settings.instagram_url && (
                      <a
                        href={settings.instagram_url}
                        target="_blank"
                        rel="noopener noreferrer"
                        className="block font-body text-maroon-700 dark:text-maroon-200 hover:text-maroon-500 text-sm transition-colors"
                      >
                        Instagram{settings.instagram_handle ? ` (${settings.instagram_handle})` : ''}
                      </a>
                    )}
                    {settings.playhq_url && (
                      <a
                        href={settings.playhq_url}
                        target="_blank"
                        rel="noopener noreferrer"
                        className="block font-body text-maroon-700 dark:text-maroon-200 hover:text-maroon-500 text-sm transition-colors"
                      >
                        PlayHQ
                      </a>
                    )}
                  </div>
                </CardContent>
              </Card>

              {/* Committee: CMS-managed (committee_members), read server-side */}
              {committee.length > 0 && (
                <Card>
                  <CardContent className="p-6">
                    <h3 className="text-xl font-display font-bold text-content-primary mb-4">Committee</h3>
                    <ul className="space-y-3">
                      {committee.map((member) => (
                        <li key={member.id} className="flex flex-wrap items-center justify-between gap-x-3 gap-y-1">
                          <span className="font-body text-content-primary">
                            {member.name}
                            {member.email && (
                              <a
                                href={`mailto:${member.email}`}
                                className="ml-2 font-body text-sm text-maroon-700 dark:text-maroon-200 hover:text-maroon-500 transition-colors"
                              >
                                {member.email}
                              </a>
                            )}
                          </span>
                          <span className="font-body text-sm text-maroon-600 dark:text-maroon-300 font-semibold">
                            {member.role}
                          </span>
                        </li>
                      ))}
                    </ul>
                  </CardContent>
                </Card>
              )}

              {/* Upcoming calendar events flagged for the contact page */}
              <ContactUpcomingEvents />

              {/* Google Maps */}
              <Card>
                <div className="overflow-hidden rounded-xl">
                  {settings.google_maps_embed_url && new URL(settings.google_maps_embed_url).searchParams.get('pb') ? <iframe
                    src={settings.google_maps_embed_url || fallbackClubSettings.google_maps_embed_url || undefined}
                    width="100%"
                    height="300"
                    style={{ border: 0 }}
                    allowFullScreen
                    loading="lazy"
                    sandbox="allow-scripts allow-same-origin allow-popups allow-popups-to-escape-sandbox"
                    referrerPolicy="strict-origin-when-cross-origin"
                    title={`Map showing ${settings.ground_name}, ${settings.address}`}
                  /> : <div className="p-6"><h2 className="text-xl font-semibold">Find us at {settings.ground_name}</h2><p className="my-3 text-content-muted">{settings.address}</p><a className="btn-secondary" href={`https://www.google.com/maps/search/?api=1&query=${encodeURIComponent(`${settings.ground_name}, ${settings.address}`)}`} target="_blank" rel="noopener noreferrer">Get directions on Google Maps</a></div>}
                </div>
              </Card>
            </div>
          </div>
          </ScrollReveal>
        </div>
      </section>
    </>
  );
}
