import Link from 'next/link';
import ScrollReveal from '@/components/common/ScrollReveal';
import { fallbackClubSettings } from '@/lib/club-settings-types';
import { getClubSettings } from '@/lib/club-settings';
import { getContentBlocks } from '@/lib/content-blocks';
import { getCommitteeMembers, type CommitteeMemberContent } from '@/lib/structured-content';
import ContactUpcomingEvents from '@/components/calendar/ContactUpcomingEvents';
import ContactForm from './ContactForm';

// Server component: CMS copy, club settings and the committee list are read
// server-side (same sources as /api/content-blocks, /api/club-settings and
// /api/public/committee) and regenerated by the segment's ISR config in
// ./layout.tsx. Only the enquiry form is a client island.

// Used in the "email notification failed" notice when club settings carry no
// email address.
// Urgent follow-up goes to the secretary inbox, as before the page moved to
// server rendering (the club settings address is shown separately below).
const URGENT_EMAIL = 'ndcc.secretary1@gmail.com';

async function loadCommittee(): Promise<CommitteeMemberContent[]> {
  try {
    const members = await getCommitteeMembers();
    return Array.isArray(members) ? members : [];
  } catch {
    return [];
  }
}

export default async function ContactPage() {
  const [blocks, settings, committee] = await Promise.all([
    getContentBlocks(['contact.hero', 'contact.form_intro', 'contact.details']),
    getClubSettings(),
    loadCommittee(),
  ]);
  const heroTitle = blocks['contact.hero']?.title || 'Contact Us';
  const heroBody = blocks['contact.hero']?.body || 'Have a question, want to join, or looking to get involved? We’d love to hear from you.';
  const formIntro = blocks['contact.form_intro']?.body || 'Fill out the form below and we’ll get back to you as soon as possible.';
  const detailsTitle = blocks['contact.details']?.title || 'Club Details';

  const clubPhoneHref = settings.phone ? `tel:${settings.phone.replace(/\s+/g, '')}` : undefined;

  const socialLinks = [
    settings.facebook_url ? { href: settings.facebook_url, label: 'Facebook' } : null,
    settings.instagram_url ? { href: settings.instagram_url, label: `Instagram${settings.instagram_handle ? ` (${settings.instagram_handle})` : ''}` } : null,
    settings.playhq_url ? { href: settings.playhq_url, label: 'PlayHQ' } : null,
  ].filter((link): link is { href: string; label: string } => link !== null);

  const valueLinkClass = 'font-body font-medium text-maroon-700 underline underline-offset-[3px] transition-colors hover:text-maroon-500 dark:text-maroon-200 break-words';

  return (
    <>
      {/* Hero */}
      <section className="page-hero px-0">
        <div className="nd-wrap">
          <nav aria-label="Breadcrumb" className="nd-crumbs">
            <Link href="/">Home</Link> / <span aria-current="page">Contact</span>
          </nav>
          <ScrollReveal onMount delay={0}><h1 className="page-hero-title">{heroTitle}</h1></ScrollReveal>
          <ScrollReveal onMount delay={0.15}><p className="page-hero-subtitle">{heroBody}</p></ScrollReveal>
        </div>
      </section>

      {/* Contact Form + Details */}
      <section className="nd-sec-tight">
        <ScrollReveal className="nd-wrap nd-two-col">
          {/* Form Column */}
          <div className="nd-card min-w-0 p-5 sm:p-[26px]">
            <h2 className="mb-2 font-display font-semibold tracking-[-0.025em] text-content-primary" style={{ fontSize: 'clamp(22px, 2.6vw, 28px)' }}>Send Us a Message</h2>
            <p className="mb-6 font-body text-content-muted">{formIntro}</p>
            <ContactForm urgentEmail={URGENT_EMAIL} />
          </div>

          {/* Details Column */}
          <div className="flex min-w-0 flex-col gap-5">
            <div className="nd-card p-5 sm:p-[26px]">
              <h2 className="mb-4 font-display text-[19px] font-semibold text-content-primary">{detailsTitle}</h2>
              <ul className="nd-contact-list">
                <li>
                  <span className="nd-contact-label">Email</span>
                  <a href={settings.email ? `mailto:${settings.email}` : undefined} className={valueLinkClass}>
                    {settings.email}
                  </a>
                </li>
                <li>
                  <span className="nd-contact-label">Phone</span>
                  <a href={clubPhoneHref} className={valueLinkClass}>
                    {settings.phone}
                  </a>
                </li>

                {/* Committee: CMS-managed (committee_members), read server-side */}
                {committee.map((member) => (
                  <li key={member.id}>
                    <span className="nd-contact-label">{member.role}</span>
                    <span className="font-body text-content-primary">
                      {member.name}
                      {member.email && (
                        <>
                          {' · '}
                          <a href={`mailto:${member.email}`} className={valueLinkClass}>
                            {member.email}
                          </a>
                        </>
                      )}
                    </span>
                  </li>
                ))}

                <li>
                  <span className="nd-contact-label">Ground</span>
                  <span className="font-body font-semibold text-content-primary">{settings.ground_name}</span>
                  <span className="font-body text-content-secondary">{settings.address}</span>
                </li>

                {socialLinks.length > 0 && (
                  <li>
                    <span className="nd-contact-label">Social Links</span>
                    <span className="flex flex-wrap gap-x-4 gap-y-1">
                      {socialLinks.map((link) => (
                        <a key={link.label} href={link.href} target="_blank" rel="noopener noreferrer" className={valueLinkClass}>
                          {link.label}
                        </a>
                      ))}
                    </span>
                  </li>
                )}
              </ul>
            </div>

            {/* Upcoming calendar events flagged for the contact page */}
            <ContactUpcomingEvents />

            {/* Google Maps */}
            <div className="nd-card overflow-hidden">
              {settings.google_maps_embed_url && new URL(settings.google_maps_embed_url).searchParams.get('pb') ? <iframe
                src={settings.google_maps_embed_url || fallbackClubSettings.google_maps_embed_url || undefined}
                width="100%"
                height="300"
                style={{ border: 0, display: 'block' }}
                allowFullScreen
                loading="lazy"
                sandbox="allow-scripts allow-same-origin allow-popups allow-popups-to-escape-sandbox"
                referrerPolicy="strict-origin-when-cross-origin"
                title={`Map showing ${settings.ground_name}, ${settings.address}`}
              /> : <div className="p-5 sm:p-[26px]"><h2 className="font-display text-[19px] font-semibold text-content-primary">Find us at {settings.ground_name}</h2><p className="my-3 text-content-muted">{settings.address}</p><a className="btn-secondary" href={`https://www.google.com/maps/search/?api=1&query=${encodeURIComponent(`${settings.ground_name}, ${settings.address}`)}`} target="_blank" rel="noopener noreferrer">Get directions on Google Maps</a></div>}
            </div>
          </div>
        </ScrollReveal>
      </section>
    </>
  );
}
