/* eslint-disable @typescript-eslint/no-explicit-any */
'use client';
import { useEffect, useState } from 'react';
import Button from '@/components/ui/Button';
import Card, { CardContent } from '@/components/ui/Card';
import Input from '@/components/ui/Input';
import { adminFetch, parseApiResponse } from '@/lib/admin-client';

const scoringFields: Array<[string,string]> = [['runPoints','Run'],['wicketPoints','Wicket'],['catchPoints','Catch'],['runoutPoints','Run-out'],['maidenPoints','Maiden'],['stumpingPoints','Stumping'],['notOutPoints','Not out'],['fiftyBonus','50-99 bonus'],['centuryBonus','100+ bonus'],['fiveWicketBonus','5-6 wicket bonus'],['sevenWicketBonus','7+ wicket bonus'],['batsmanRunMultiplier','BAT run multiplier'],['allRounderRunMultiplier','AR run multiplier'],['allRounderWicketMultiplier','AR wicket multiplier'],['bowlerWicketMultiplier','BOWL wicket multiplier'],['wicketKeeperRunMultiplier','WK run multiplier'],['wicketKeeperCatchMultiplier','WK catch multiplier'],['captainMultiplier','Captain multiplier'],['viceCaptainMultiplier','Vice-captain multiplier']];
export default function AdminFantasySettingsPage() {
  const [form,setForm]=useState<any>(null); const [readiness,setReadiness]=useState<any>(null); const [message,setMessage]=useState('');
  useEffect(()=>{adminFetch('/api/admin/fantasy/settings').then(parseApiResponse<any>).then((r)=>{setForm(r.settings);setReadiness(r.readiness);}).catch((e)=>setMessage(e.message));},[]);
  const set=(key:string,value:any)=>setForm((f:any)=>({...f,[key]:value}));
  const save=async()=>{setMessage('');try{const r=await parseApiResponse<any>(await adminFetch('/api/admin/fantasy/settings',{method:'PATCH',headers:{'Content-Type':'application/json'},body:JSON.stringify(form)}));setReadiness(r.readiness);setMessage('Dino Coach settings saved.');}catch(e){setMessage(e instanceof Error?e.message:'Save failed.');}};
  if(!form)return <p role="status">Loading Dino Coach settings... {message}</p>;
  return <div className="space-y-6"><div><h1 className="text-2xl font-display font-bold">Dino Coach settings</h1><p className="text-sm text-content-muted">Committee controls for the current competition. Launch controls cannot bypass player readiness.</p></div>
    <Card><CardContent className="p-5"><h2 className="text-lg font-bold">Release gate</h2><p className={readiness?.ready?'text-green-700':'text-amber-800'}>{readiness?.ready?'All player identity and price prerequisites pass.':(readiness?.blockers||['Readiness has not been calculated.']).join(' ')}</p><div className="mt-3 grid gap-3 sm:grid-cols-3">{[['public_launch_enabled','Public launch'],['registration_open','Registration'],['team_selection_open','Team selection']].map(([key,label])=><label key={key} className="flex gap-2"><input type="checkbox" checked={Boolean(form[key])} onChange={(e)=>set(key,e.target.checked)}/>{label}</label>)}</div></CardContent></Card>
    <Section title="General and entry"><div className="grid gap-4 md:grid-cols-2"><Input id="brand" label="Brand name" value={form.brand_name} onChange={(e)=>set('brand_name',e.target.value)}/><Input id="rules" label="Rules version" value={form.rules_version} onChange={(e)=>set('rules_version',e.target.value)}/><Input id="fee" label="Entry fee - cents AUD" type="number" value={form.entry_fee_cents} onChange={(e)=>set('entry_fee_cents',Number(e.target.value))}/><Input id="age" label="Minimum age" type="number" value={form.minimum_age} onChange={(e)=>set('minimum_age',Number(e.target.value))}/><Input id="notify" label="Notification recipients - comma separated" value={(form.notification_recipients||[]).join(', ')} onChange={(e)=>set('notification_recipients',e.target.value.split(','))}/></div><label className="block mt-4 text-sm font-semibold">Pilot notice<textarea className="form-input mt-1 w-full min-h-32" value={form.pilot_notice} onChange={(e)=>set('pilot_notice',e.target.value)}/></label></Section>
    <Section title="Squad and pricing"><div className="grid gap-4 md:grid-cols-3"><NumberField label="Budget - Dino Dollars" field="budget_dino_dollars" form={form} set={set}/><NumberField label="Initial floor" field="initial_price_floor_dino_dollars" form={form} set={set}/><NumberField label="Initial ceiling" field="initial_price_ceiling_dino_dollars" form={form} set={set}/><NumberField label="Dino Dollars per performance point" field="price_point_value_dino_dollars" form={form} set={set}/><NumberField label="Price changes start round" field="price_changes_start_round" form={form} set={set}/><Input id="rollover" label="Rollover strategy" value={form.rollover_strategy||''} onChange={(e)=>set('rollover_strategy',e.target.value)}/></div><p className="mt-3 text-sm text-content-muted">Fixed slots: XI 4 BAT, 2 AR, 1 WK, 4 BOWL; bench 1 of each. Transfer window: Monday 09:00 to Saturday 11:00 Australia/Melbourne; unlimited and free.</p></Section>
    <Section title="Scoring"><div className="grid gap-4 sm:grid-cols-2 lg:grid-cols-4">{scoringFields.map(([key,label])=><Input key={key} id={key} label={label} type="number" step="0.25" value={form.scoring_config?.[key]??0} onChange={(e)=>set('scoring_config',{...form.scoring_config,[key]:Number(e.target.value)})}/>)}</div></Section>
    <Section title="Moderation and prizes"><div className="grid gap-4 md:grid-cols-2"><Input id="blocked" label="Blocked team-name terms - comma separated" value={(form.blocked_team_name_terms||[]).join(', ')} onChange={(e)=>set('blocked_team_name_terms',e.target.value.split(',').map((v)=>v.trim()).filter(Boolean))}/><NumberField label="Round-robin prize - Dino Dollars" field="round_robin_prize_dino_dollars" form={form} set={set}/><Input id="prize-label" label="Highest squad-value prize label" value={form.squad_value_prize_label||''} onChange={(e)=>set('squad_value_prize_label',e.target.value)}/><Input id="prize-description" label="Highest squad-value prize description" value={form.squad_value_prize_description||''} onChange={(e)=>set('squad_value_prize_description',e.target.value)}/></div></Section>
    {message&&<p role="status" className="text-sm">{message}</p>}<Button onClick={save}>Save Dino Coach settings</Button></div>;
}
function Section({title,children}:{title:string;children:React.ReactNode}){return <Card><CardContent className="p-5"><h2 className="mb-4 text-lg font-bold">{title}</h2>{children}</CardContent></Card>}
function NumberField({label,field,form,set}:{label:string;field:string;form:any;set:(k:string,v:any)=>void}){return <Input id={field} label={label} type="number" value={form[field]} onChange={(e)=>set(field,Number(e.target.value))}/>}
