'use client';
import {useCallback,useEffect,useState} from 'react';
import {adminFetch,parseApiResponse} from '@/lib/admin-client';
import Button from '@/components/ui/Button';
type Collection={id:string;payment_reference:string;amount_cents:number;cash_received_at:string;cash_handed_in_at:string|null;member:{full_name:string}|null;staff:{full_name:string}|null};
export default function CashCollections(){
 const [rows,setRows]=useState<Collection[]>([]);const [error,setError]=useState('');const [ready,setReady]=useState(false);const [busy,setBusy]=useState(false);const [confirm,setConfirm]=useState<string|null>(null);
 const load=useCallback(async()=>{setError('');try{const data=await parseApiResponse<{collections:Collection[]}>(await adminFetch('/api/admin/raffle/cash-collections'));setRows(data.collections);setReady(true);}catch(e){setError(e instanceof Error?e.message:'Unable to load cash collections.');}},[]);
 useEffect(()=>{void load();},[load]);
 const receive=async(id:string)=>{setBusy(true);setError('');try{await parseApiResponse(await adminFetch('/api/admin/raffle/cash-collections',{method:'PATCH',headers:{'Content-Type':'application/json'},body:JSON.stringify({orderId:id,cashReceived:true})}));setConfirm(null);await load();}catch(e){setError(e instanceof Error?e.message:'Unable to record cash handover.');}finally{setBusy(false);}};
 const outstanding=rows.filter(row=>!row.cash_handed_in_at);
 return <section className="rounded-lg border border-edge-subtle p-5 space-y-3"><h2 className="text-xl font-bold">Trailer raffle cash to hand in</h2><p>Member collections only. Record receipt here after the member gives the cash to the club. Committee sales already record cash received by the club. Tickets are issued when the buyer pays the collector.</p>{error&&<p role="alert">{error}</p>}<Button variant="secondary" onClick={load} disabled={busy}>Refresh cash collections</Button>{ready&&<><p className="font-semibold">Outstanding: AUD ${(outstanding.reduce((sum,row)=>sum+row.amount_cents,0)/100).toFixed(2)}</p>{!outstanding.length?<p>No cash sales awaiting handover.</p>:<ul className="space-y-3">{outstanding.map(row=><li key={row.id} className="border rounded-lg p-3 space-y-2"><p><strong>{row.member?.full_name||row.staff?.full_name||'Recorded collector'}</strong> - AUD ${(row.amount_cents/100).toFixed(2)}</p><p className="text-sm">{row.payment_reference} - collected {new Date(row.cash_received_at).toLocaleString('en-AU')}</p>{confirm===row.id?<div className="flex flex-wrap gap-2"><Button disabled={busy} onClick={()=>receive(row.id)}>Confirm club received this cash</Button><Button disabled={busy} variant="secondary" onClick={()=>setConfirm(null)}>Cancel</Button></div>:<Button disabled={busy} variant="secondary" onClick={()=>setConfirm(row.id)}>Record cash handed to club</Button>}</li>)}</ul>}<p className="text-sm">{rows.length-outstanding.length} cash sales reconciled.</p></>}</section>;
}
