INSERT INTO fantasy_dino_settings(season_id,pilot_notice,slot_counts,scoring_config,registration_open,team_selection_open,public_launch_enabled)
SELECT id,
'Dino Coach is running as a pilot for the 2026/2027 season. Feedback and suggestions are welcome. The league may make reasonable, communicated adjustments during the season to correct scoring, data or technical issues and protect fair operation.',
'{"starter":{"BAT":4,"AR":2,"WK":1,"BOWL":4},"bench":{"BAT":1,"AR":1,"WK":1,"BOWL":1}}'::JSONB,
'{"runPoints":1,"wicketPoints":10,"catchPoints":10,"runoutPoints":10,"maidenPoints":5,"stumpingPoints":10,"notOutPoints":10,"fiftyBonus":20,"centuryBonus":50,"fiveWicketBonus":25,"sevenWicketBonus":50,"batsmanRunMultiplier":1.75,"allRounderRunMultiplier":1.5,"allRounderWicketMultiplier":1.5,"bowlerWicketMultiplier":2,"wicketKeeperRunMultiplier":1.5,"wicketKeeperCatchMultiplier":1.5,"captainMultiplier":2,"viceCaptainMultiplier":2,"benchScores":false,"stackBattingMilestones":false,"stackBowlingMilestones":false}'::JSONB,
FALSE,FALSE,FALSE FROM fantasy_seasons WHERE is_current=TRUE ON CONFLICT(season_id) DO NOTHING;
UPDATE fantasy_settings SET season_name='Dino Coach',squad_budget=2.0,max_players_per_role='{"WK":2,"BAT":5,"AR":3,"BOWL":5}'::JSONB,free_transfers_per_round=999999,transfer_penalty_points=0,is_registration_open=FALSE,is_team_selection_open=FALSE,updated_at=NOW() WHERE season_id IN (SELECT id FROM fantasy_seasons WHERE is_current=TRUE);
INSERT INTO fantasy_scoring_rules(key,label,points,enabled,description) VALUES
('runs','Runs',1,TRUE,'Points per run.'),('wickets','Wickets',10,TRUE,'Points per wicket.'),('maidens','Maidens',5,TRUE,'Points per maiden over.'),('catches','Catches',10,TRUE,'Points per catch.'),('runouts','Run outs',10,TRUE,'Points per run-out.'),('stumpings','Stumpings',10,TRUE,'Points per stumping.'),('ducks','Ducks',0,TRUE,'No duck penalty.'),('not_out_bonus','Not out bonus',10,TRUE,'Bonus for finishing not out.'),('player_of_match_bonus','Player of match bonus',0,TRUE,'No player-of-the-match points.'),('fifty_bonus','Fifty bonus',20,TRUE,'Exclusive bonus for 50 to 99 runs.'),('century_bonus','Century bonus',50,TRUE,'Exclusive bonus for 100 or more runs.'),('five_wicket_bonus','Five-wicket bonus',25,TRUE,'Exclusive bonus for five or six wickets.'),('seven_wicket_bonus','Seven-wicket bonus',50,TRUE,'Exclusive bonus for seven or more wickets.')
ON CONFLICT(key) DO UPDATE SET label=EXCLUDED.label,points=EXCLUDED.points,enabled=EXCLUDED.enabled,description=EXCLUDED.description,updated_at=NOW();
