'use client';
import {useCallback,useEffect,useState} from 'react';
import Link from 'next/link';
import Button from '@/components/ui/Button';
import Input from '@/components/ui/Input';
type RecordRow={source:string;id:string;full_name:string;email:string;phone:string;member_type:string;status:string};
export default function MemberDirectory(){
 const [records,setRecords]=useState<RecordRow[]>([]);const [total,setTotal]=useState(0);const [page,setPage]=useState(0);const [search,setSearch]=useState('');const [filter,setFilter]=useState('');const [error,setError]=useState('');const [busy,setBusy]=useState(false);
 const load=useCallback(async()=>{setBusy(true);setError('');try{const res=await fetch(`/api/admin/memberships/directory?page=${page}&search=${encodeURIComponent(filter)}`,{cache:'no-store'});const data=await res.json();if(!res.ok)throw new Error(data.error||'Could not load records.');setRecords(data.records);setTotal(data.total);}catch(reason){setError(reason instanceof Error?reason.message:'Could not load records.');}finally{setBusy(false);}},[page,filter]);
 useEffect(()=>{void load();},[load]);
 const add=async(e:React.FormEvent<HTMLFormElement>)=>{e.preventDefault();const form=e.currentTarget;const fields=Object.fromEntries(new FormData(form));setBusy(true);setError('');try{const res=await fetch('/api/admin/memberships/directory',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(fields)});const result=await res.json();if(!res.ok)throw new Error(result.error);form.reset();await load();}catch(reason){setError(reason instanceof Error?reason.message:'Unable to add member.');}finally{setBusy(false);}};
 return <div className="space-y-6"><Link href="/admin/memberships" className="underline">Membership settings</Link><h1 className="text-3xl font-bold">Club member directory</h1><p>Private club records, social applications and Dino Coach registrations. Source records are kept separately; shared email addresses do not automatically merge people. PlayHQ registrations must be added from the club&apos;s authorised registration records.</p>
 <form onSubmit={e=>{e.preventDefault();setPage(0);setFilter(search);}} className="flex gap-3"><Input id="member-search" label="Search name or email" value={search} onChange={e=>setSearch(e.target.value)} /><Button disabled={busy}>Search</Button></form>
 {error&&<p role="alert">{error} <button onClick={load} className="underline">Retry</button></p>}<p role="status">{busy?'Loading...':`${total} source records`}</p>
 <div className="overflow-x-auto"><table className="w-full text-left text-sm"><thead><tr>{['Name','Email','Phone','Type','Source','Status'].map(x=><th className="p-3" key={x}>{x}</th>)}</tr></thead><tbody>{records.map(r=><tr className="border-t" key={`${r.source}:${r.id}`}><td className="p-3">{r.full_name}</td><td className="p-3">{r.email}</td><td className="p-3">{r.phone}</td><td className="p-3">{r.member_type}</td><td className="p-3">{r.source.replaceAll('_',' ')}</td><td className="p-3">{r.status}</td></tr>)}</tbody></table></div>
 <div className="flex gap-3"><Button disabled={busy||page===0} onClick={()=>setPage(page-1)}>Previous</Button><Button disabled={busy||(page+1)*100>=total} onClick={()=>setPage(page+1)}>Next</Button></div>
 <details><summary className="cursor-pointer font-bold">Add a player or social member</summary><form onSubmit={add} className="mt-4 max-w-xl space-y-3"><Input id="member-name" name="full_name" label="Full name" maxLength={120} required/><Input id="member-email" name="email" label="Email" type="email" required/><Input id="member-phone" name="phone" label="Phone (optional)" maxLength={40}/><label className="block">Member type<select name="member_type" className="form-input w-full"><option value="player">Player</option><option value="social">Social</option><option value="both">Player and social</option></select></label><p className="text-sm">Only enter details supplied for club administration. This creates a contact record, without creating a login or sending an email.</p><Button disabled={busy}>Add member record</Button></form></details>
 </div>;
}
